# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: lambdausers
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: lambda-users-app
# "service" is the name of this project. This will also be added to your AWS resource names.
service: lambda-users

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:*
        - sns:Publish
      Resource:
        - arn:aws:dynamodb:us-east-1:861276089505:table/UserTable
        - arn:aws:sns:us-east-1:861276089505:snsusers

functions:
  hello:
    handler: src/hello.hello
    events:
      - httpApi:
          path: /
          method: get
  create:
    handler: src/addUser.addUser
    events:
      - httpApi:
          path: /users
          method: post
  getUsers:
    handler: src/getUsers.getUsers
    events:
      - httpApi:
          path: /users
          method: get
  getUser:
    handler: src/getUser.getUser
    events:
      - httpApi:
          path: /user/{id}
          method: get
  updateUser:
    handler: src/updateUser.updateUser
    events:
      - httpApi:
          path: /user/{id}
          method: put
  deleteUser:
    handler: src/deleteUser.deleteUser
    events:
      - httpApi:
          path: /user/{id}
          method: delete
  sendEmail:
    handler: src/sendEmail.sendEmail
    events:
      - httpApi:
          path: /send-email
          method: post

resources:
  Resources:
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UserTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
